config/routes.rb
Pdfpo::Application.routes.draw do
  post "webhooks/postmark"

  resources :purchase_orders do
    resources :authorizations
    member do 
      post "email"
    end
  end

  root :to => 'purchase_orders#new'

end

app/models/purchase_order.rb
class PurchaseOrder < ActiveRecord::Base

  has_many :line_items
  has_many :authorizations
  has_many :notes

  attr_accessible :budget, :email, :date, :delivery_address, :number, :raised_by, :supplier_name, :your_company_name, :line_items_attributes, :status, :conversation_key, :phone_number, :note


  before_create :generate_conversation_key


  accepts_nested_attributes_for :line_items


  def total

  	line_items.sum("price * quantity")
  	
  end


  def total_including_tax

  	line_items.each.sum do |li|

  		li.quantity * li.price.to_f * (1 + ( li.tax_rate.to_f / 100 ))


  	end


  	
  end




  def to_label

  	"#{your_company_name} #{raised_by} Purchase Order #{number}".parameterize
  	
  end


  private



  def generate_conversation_key
    self.conversation_key = SecureRandom.hex(5)
  end 

end

app/controllers/purchase_orders_controller.rb
class PurchaseOrdersController < ApplicationController
  # GET /purchase_orders
  # GET /purchase_orders.json

  def index

    render file: "#{Rails.root}/public/404.html" unless params[:secure].present?
    @purchase_orders = PurchaseOrder.last(30)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @purchase_orders }
    end
  end

  # GET /purchase_orders/1
  # GET /purchase_orders/1.json
  def show
    @purchase_order = PurchaseOrder.find(params[:id])


    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @purchase_order }
      format.pdf do
        # headers['Content-Disposition'] = "attachment; filename=#{@purchase_order.to_label}"
      
        pdf = render pdf: "show", encoding: 'utf8', layout: "pdf", disposition: "attachment", :footer => {:html => {:template => 'layouts/footer.html.haml'}}

      end
    end
  end


  def email

    @purchase_order = PurchaseOrder.find params[:id]
    PurchaseOrderMailer.send_email( params[:recipient], params[:message], @purchase_order).deliver!
    flash[:success] = "Purchase Order Emailed"
    redirect_to purchase_order_path(@purchase_order)
    
  end
  # GET /purchase_orders/new
  # GET /purchase_orders/new.json
  def new

    @purchase_order = PurchaseOrder.new session[:preset]

    session[:last_purchase_order_number] ||= 0
    session[:last_purchase_order_number] = session[:last_purchase_order_number] + 1

    @purchase_order.number =  session[:last_purchase_order_number] 

    @purchase_order.line_items.clear

    3.times do 
      @purchase_order.line_items.build quantity: 1
    end

    @purchase_order.date = Date.today


    respond_to do |format|
      format.html 
      format.json { render json: @purchase_order }
    end
  end

  # GET /purchase_orders/1/edit
  def edit
    @purchase_order = PurchaseOrder.find(params[:id])
  end

  # POST /purchase_orders
  # POST /purchase_orders.json
  def create

    @purchase_order = PurchaseOrder.new(params[:purchase_order])
    @purchase_order.status = "Not Authorized"

    unless @purchase_order.line_items.count == 1
      @purchase_order.line_items = @purchase_order.line_items.select do |li| li.description.present? end
    end

    session[:preset] = params[:purchase_order]

    respond_to do |format|
      if verify_recaptcha(:model => @purchase_order, :message => "Oh! It's error with reCAPTCHA!") && @purchase_order.save
        format.html { redirect_to purchase_order_path(@purchase_order )}
        format.json { render json: @purchase_order, status: :created, location: @purchase_order }
      else
        format.html { render action: "new" }
        format.json { render json: @purchase_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /purchase_orders/1
  # PUT /purchase_orders/1.json
  def update
    @purchase_order = PurchaseOrder.find(params[:id])

    respond_to do |format|
      if @purchase_order.update_attributes(params[:purchase_order])
        format.html { redirect_to @purchase_order, notice: 'Purchase order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @purchase_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchase_orders/1
  # DELETE /purchase_orders/1.json
  def destroy
    @purchase_order = PurchaseOrder.find(params[:id])
    @purchase_order.destroy

    respond_to do |format|
      format.html { redirect_to purchase_orders_url }
      format.json { head :no_content }
    end
  end



  def edit

    @purchase_order = PurchaseOrder.find params[:id]

    if @purchase_order.line_items.empty?
      3.times do @purchase_order.line_items.build( quantity: 1) end
    end





    
  end
end

app/helpers/purchase_orders_helper.rb
module PurchaseOrdersHelper
  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
  end
  
  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize  , :f => builder)
    end
    link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
  end
 
end


def class_for(purchase_order)


end


def disable_download po

	if po.status == "Authorized"
		false
	else
		true
	end
	
end

app/views/purchase_orders/_form.html.haml
.large-12.columns
  = form_for @purchase_order do |f|
    - if @purchase_order.errors.any?
      #error_explanation
        %h2= "#{pluralize(@purchase_order.errors.count, "error")} prohibited this purchase_order from being saved:"
        %ul
          - @purchase_order.errors.full_messages.each do |msg|
            %li= msg

    .large-6.columns
      .field
        = f.label :number, "Purchase Order Number"
        = f.number_field :number
    .large-6.columns
      .field
        = f.label :date
        = f.text_field :date, data: {type: :date}

    .large-6.columns
      
      %h6 Your Company Details
      .field
        = f.label :your_company_name, "Company Name"
        = f.text_field :your_company_name
      .field
        = f.label :delivery_address
        = f.text_area :delivery_address
      .field
        = f.label :raised_by
        = f.text_field :raised_by
      .field
        = f.label :phone_number, "Your Contact Number"
        = f.text_field :phone_number
      .field
        = f.label :email, "Contact Email"
        = f.text_field :email
      
    .large-6.columns
      %h6 Supplier Details
      .field
        = f.label :supplier_name
        = f.text_field :supplier_name
    .large-12.columns
      %h3 Items
      = f.fields_for :line_items do |li|
        = render "line_item" , f: li
    .large-12.columns
      .right= link_to_add_fields "Add Line", f, :line_items
    .large-12.columns
      = f.label :note, "Additional Notes"
      = f.text_area :note

      .actions
        %br/
        = recaptcha_tags if @purchase_order.new_record?
        %br/
        %br/
        = f.submit 'Save & Download', class: :button

app/views/purchase_orders/_line_item.html.haml
.line_item.fields.row
  .large-5.columns.field
    = f.text_area :description, placeholder: "Description"
  .large-2.columns.field
    = f.text_field :quantity, placeholder: "Qty"

  .large-2.columns.field
    = f.text_field :tax_rate, placeholder: "Tax Rate"
  .large-2.columns.field
    = f.text_field :price, placeholder: "Unit Price"
  .large-1.columns.inline
    = link_to_remove_fields "&times;".html_safe, f

app/views/purchase_orders/_purchase_order_detail.html.haml
%h1 
  Purchase Order
.small
  %strong= @purchase_order.your_company_name
  = @purchase_order.delivery_address

%br/

.row
  .large-6.columns
    %p
      %label PO #:
      = @purchase_order.number
      = @purchase_order.budget
  .large-5.columns
    %p
      %label Date:
      = @purchase_order.date
.row
  .large-6.columns

    %p 
      %label Raise by
      = @purchase_order.raised_by
    %p
      %label Phone:
      = @purchase_order.phone_number

    %p
      %label Email:
      = @purchase_order.email



  .large-6.columns
    %p
      %b Supplier name:
      = @purchase_order.supplier_name

  



%table{ style: "width:100%;"}
  %thead
    %tr
      %td #
      %td Item
      %td Quantity
      %td Tax
      %td Unit Cost
      %td Total

  - @purchase_order.line_items.each_with_index do |line_item, index|
    %tr
      %td= index + 1
      %td{ width: "50%"}
        = simple_format line_item.description
      %td{ width: "10%"}
        = line_item.quantity
      %td{ width: "10%"}
        = line_item.tax_rate
      %td{ width: "10%"}
        = number_to_currency line_item.price, unit: default_currency
      %td{ width: "10%" }
        = number_to_currency line_item.total, unit: default_currency


  %tfoot
    %tr
      %td
      %td
      %td{ colspan: 2} Total ex Tax
      %td=  number_to_currency @purchase_order.total, unit: default_currency
    %tr
      %td
      %td
      %td{ colspan: 2} Total Inc Tax
      %td= number_to_currency @purchase_order.total_including_tax, unit: default_currency

.row
  .large-12.columns
    %label Notes
    %p#note
      = "None" if @purchase_order.note.blank?
      = @purchase_order.note 

.row
  .large-2.columns.signature_label
    %label Signed By
  .large-4.columns
    #signature_line

  .large-2.columns.signature_label
    %label Date
  .large-4.columns
    #signature_line

app/views/purchase_orders/edit.html.haml
.row
	.large-12.columns
		.panel.columns
			%h1 Edit Purchase Order

			= render 'form'

app/views/purchase_orders/index.html.haml
%h1 Purchase Orders
%table
  %tr
    %th Number
    %th Phone Number
    %th Email
    %th Raised by
    %th Your company name
    %th Supplier name
    %th Delivery address
    %th
    %th
    %th

  - @purchase_orders.each do |purchase_order|
    %tr
      %td= purchase_order.number
      %td= purchase_order.phone_number
      %td= purchase_order.email
      %td= purchase_order.raised_by
      %td= purchase_order.your_company_name
      %td= purchase_order.delivery_address
      %td= purchase_order.supplier_name
      %td= link_to 'Show', purchase_order
      %td= link_to 'Edit', edit_purchase_order_path(purchase_order)
      %td= link_to 'Destroy', purchase_order, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Purchase order', new_purchase_order_path

app/views/purchase_orders/new.html.haml
.row
	.large-9.columns
		.panel.columns
			%h2 Create Your Purchase Order
			= render 'form'

		.panel.columns{ style: "padding-top:10px"}
			%h3 Get More Features
			%p
				This tool is provided free of charge by 
				%a{ href: "http://www.rubberstamp.io"} RubberStamp.io
				a powerful online purchase order management solution.  Features include:
				.panel
					%ul
						%li Customized PDF Templates
						%li Product and Supplier Listing
						%li Multi user access and approval process
						%li Password protection and SSL Security
						%li Budgeting
						%li Mobile Access
						%li Reporting

			.right
				%a{ href: "https://app.rubberstamp.io/users/sign_up"}
					%img{ src: "/images/learn_more_button.png"}

	





	.large-3.columns.panel
		%h3 How to use this form
		%p
			Simply enter your details and press the 
			%code Save & Download
			button to download your Purchase Order.  You can enter any Purchase Order Number you like and the detail on the purchase order should include your
			own company name and the name of the person who has raised the purchase order.  

		%h5 Purchase Order Number
		%p
			Enter any unique positive number you like.  Keep a record of your purchase invoice and send this number to the supplier.  When you receive the goods you can then check the purchase order document against what was delivered.  When the supplier's invoice arrives, you can also check it against what was ordered.


		%h5 Raised By
		%p
			Enter your name or the name of the person that has authorized this purchase.  Should there be any queries on the purchase, this person can be referenced to straighten things out.

		%h5 Your Company Name
		%p
			Supply your company name so that the supplier knows who they are dealing with when they receive your purchase order.

		%h5 Delivery Address
		%p
			Where the ordered goods should be delivered to.  You may want to include a reference number here or instructions on when the items should be delivered.

		%h5 Items
		%p
			There are three spaces here for each of the Purchase Order Item details.  The <code>description</code> should describe the particular product by name eg:  "Dell XPS 5000".  The <code>Qty</code> field should indicate how many are to be delivered.  If there is a <code>Tax Rate</code> applicable, enter it in the following field.  Finally, put the <code>Unit Price</code> of a single item (no the total cost o all items). 


%script
	analytics.track("Landing Page")

app/views/purchase_orders/show.html.haml
.row
  .large-9.columns
    .panel
      = render "purchase_order_detail"
  .large-3.columns
    .xpanel
      %br/
      = link_to "Download As PDF", purchase_order_path(@purchase_order, format: :pdf), class: "button expand track_clicks", id: "download_pdf_link"
      = link_to "Request Approval", new_purchase_order_authorization_path( @purchase_order ), class: "button secondary expand track_clicks"
      = link_to "Edit Purchase Order", edit_purchase_order_path( @purchase_order ), class: "button secondary expand track_clicks"
      = link_to "New Purchase Order", new_purchase_order_path, class: "button secondary expand track_clicks"
      %a.button.secondary.expand.track_clicks{ href: "javascript:void", "data-reveal-id" => "email_purcahse_order"} Email Purchase Order

      %dl.sub-nav
        %dt Currency
        %dd{ class: default_currency == "$" ? "active" : ""}
          %a{href: "?currency=$"} $
        %dd{ class: default_currency == "&pound;" ? "active" : ""}
          = link_to "&pound;".html_safe, "?currency=#{CGI.escape "&pound;"}"
        %dd{ class: default_currency == "&euro;" ? "active" : ""}
          = link_to "&euro;".html_safe, "?currency=#{CGI.escape "&euro;"}"

      = link_to "Back", :back



#email_purcahse_order.reveal-modal{ "reveal-modal" => true}
  .row
    .offset-large-3.large-6.columns
      = form_tag  email_purchase_order_path(@purchase_order) do
        %label Recipient
        = text_field_tag :recipient
        %label Message
        = text_area_tag :message
        .actions
          = submit_tag "Send", class: :button

  

- unless @purchase_order.notes.empty?
  .row
    .large-12.columns
      - @purchase_order.notes.each do |note|
        .panel
          = simple_format note.content

.row
  .large-12.columns
 

%script
  analytics.track("Show PO")
  - unless @purchase_order.email.blank?
    - props = { "Phone Number" => @purchase_order.phone_number, name: @purchase_order.raised_by , email: @purchase_order.email, address: @purchase_order.delivery_address }
    analytics.identify("#{@purchase_order.email}", #{raw props.to_json});

= render partial: "/layouts/adwords_conversion"

app/views/purchase_orders/show.pdf.haml
%img{ src: "http://localhost:3000/images/100x100_icon.png"}
%h1 
  Purchase Order 
.small
  %strong= @purchase_order.your_company_name
  = @purchase_order.delivery_address

%br/

.row
  .large-6.columns
    %p
      %label PO #:
      = @purchase_order.number
      = @purchase_order.budget
  .large-5.columns
    %p
      %label Date:
      = @purchase_order.date
.row
  .large-6.columns

    %p 
      %label Raise by
      = @purchase_order.raised_by
    %p
      %label Phone:
      = @purchase_order.phone_number

    %p
      %label Email:
      = @purchase_order.email



  .large-6.columns
    %p
      %b Supplier name:
      = @purchase_order.supplier_name

  



%table{ style: "width:100%;"}
  %thead
    %tr
      %td #
      %td Item
      %td Quantity
      %td Tax
      %td Unit Cost
      %td Total

  - @purchase_order.line_items.each_with_index do |line_item, index|
    %tr
      %td= index + 1
      %td{ width: "50%"}
        = simple_format line_item.description
      %td{ width: "10%"}
        = line_item.quantity
      %td{ width: "10%"}
        = line_item.tax_rate
      %td{ width: "10%"}
        = number_to_currency line_item.price, unit: default_currency
      %td{ width: "10%" }
        = number_to_currency line_item.total, unit: default_currency


  %tfoot
    %tr
      %td
      %td
      %td{ colspan: 2} Total ex Tax
      %td=  number_to_currency @purchase_order.total, unit: default_currency
    %tr
      %td
      %td
      %td{ colspan: 2} Total Inc Tax
      %td= number_to_currency @purchase_order.total_including_tax, unit: default_currency

.row
  .large-12.columns
    %label Notes
    %p#note
      = "None" if @purchase_order.note.blank?
      = @purchase_order.note 

.row
  .large-2.columns.signature_label
    %label Signed By
  .large-4.columns
    #signature_line

  .large-2.columns.signature_label
    %label Date
  .large-4.columns
    #signature_line