config/routes.rb
Pdfpo::Application.routes.draw do
  post "webhooks/postmark"

  resources :purchase_orders do
    resources :authorizations
    member do 
      post "email"
    end
  end

  root :to => 'purchase_orders#new'

end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
  attr_accessible :authorization_key, :authorized, :email, :purchaseo_order_id, :sender_email

  before_create :generate_authorization_key

  belongs_to :purchase_order


  validates :authorization_key, uniqueness: true
  validates :email, presence: true



  private

  def generate_authorization_key
  	self.authorization_key = SecureRandom.hex(5)
  end
end

app/controllers/authorizations_controller.rb
class AuthorizationsController < ApplicationController


	def show

		if auth = Authorization.find_by_authorization_key( params[:id] )
			po = auth.purchase_order
			po.update_attributes status: params[:status]

			AuthorizationsMailer.notify_update_to_purchase_order( auth ).deliver!

			auth.update_attributes authorized: true
			auth.purchase_order.notes.create content: "Updated to #{params[:status]} by #{auth.email}"
			redirect_to purchase_order_path( auth.purchase_order ), notice: "Purchase Order Approved"
		else
			render file: "#{Rails.root}/public/404.html", status: 404
		end

	
	end


	def create

		@purchase_order = PurchaseOrder.find params[:purchase_order_id]

		auth = @purchase_order.authorizations.create params[:authorization]
		AuthorizationsMailer.request_authorization( auth ).deliver!
		
    flash[:success] = "Authorisation Request Sent"
		redirect_to purchase_order_path @purchase_order
	end


	def new

		@purchase_order = PurchaseOrder.find params[:purchase_order_id]
		@authorization = @purchase_order.authorizations.new
		
	end
end

app/helpers/authorizations_helper.rb
module AuthorizationsHelper
end

app/views/authorizations/new.html.haml
.row{ style: "margin-top:10px"}
	.large-offset-3.large-6.columns
		.panel
			%h4 Send an Authorization Request
			= form_for @authorization, url: purchase_order_authorizations_path(@purchase_order) do |f|
				.fields
					= f.label :sender_email, "Your Email"
					= f.text_field :sender_email, placeholder: "Your email address"
					= f.label :email, "The authorizors email address"
					= f.text_field :email, placeholder: "The Approvers Email Address"
				.actions
					= f.submit "Send Request", class: :button


%script
	analytics.track("New Authorisation Page")